# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    param_fetcher_listener:  true
    body_converter:
        enabled: true

handcraftedinthealps_rest_routing:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
    routing_loader:
        default_format: json
        include_format: false
#    view:
#        view_response_listener:  true
#        formats:
#          json: true    view:

#    exception:
#        enabled: true

#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.

#    format_listener:
#        rules:
#            - { path: '^/', fallback_format: json, priorities: [ json ] }
