#index:
#    path: /
#    controller: App\Controller\DefaultController::index
lists:
  type: rest
  resource: App\Controller\ListController
  prefix: api
events:
  type: rest
  resource: App\Controller\EventController
  prefix: api